language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run --source pydesk -m unittest discover -s tests

after_success:
  - codecov
