codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 70..100
  round: nearest
  precision: 2

  status:
    project:
      default:
        threshold: 0
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
